# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b54b486eee77f70b0a198d1c9548148518f4f4c6614cb0bd2b2ef11b9262528e39af47183e4f0a52f7e10a1a61f701b743b2a7b085b427efade08045fb0294c

test:
  secret_key_base: b6e76a35d29a3c8c16eccbf3b3921982e28e103e35aaae23b59af0c7750733f78e9ff5386f227268ebafe90df1de0b3dc6086f001bc48b284b5850e28b05b16a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
